import {
  createUIMessageStream,
  createUIMessageStreamResponse,
} from "ai";

const LESSON_PLANS: Record<string, string> = {
  default: `# Lesson Plan: {topic}

## Learning Objectives
By the end of this lesson, students will be able to:
- Define and explain the core concepts of {topic}
- Identify real-world examples related to {topic}
- Demonstrate understanding through hands-on activities

## Materials Needed
- Whiteboard and markers
- Printed handouts with key vocabulary
- Interactive worksheet (attached)
- Colored pencils or markers for student activities

## Introduction (10 minutes)
Begin the lesson by asking students: "What do you already know about {topic}?"

Write their responses on the board to activate prior knowledge and create engagement. Show a short 2-minute video clip that introduces the main concepts. This primes students for deeper exploration.

## Direct Instruction (15 minutes)
Present the key concepts using the prepared slides:

1. **Core Concept 1**: Explain the fundamental principles of {topic}
2. **Core Concept 2**: Show how these principles connect to everyday life
3. **Core Concept 3**: Demonstrate with real-world examples that students can relate to

Use think-alouds to model your reasoning process. Pause frequently to check for understanding with thumbs up/down.

## Guided Practice (15 minutes)
Students work in pairs to complete the guided worksheet on {topic}. Circulate the room to check understanding and provide targeted feedback.

**Key Questions to Ask:**
- "Can you explain this concept in your own words?"
- "How does this connect to what we learned last week?"
- "What would happen if we changed this variable?"

## Independent Practice (10 minutes)
Students complete the independent activity:
- Create a concept map showing the relationships between key ideas in {topic}
- Write a short paragraph explaining {topic} to a younger student
- Sketch a diagram that illustrates the main process

## Assessment & Closure (5 minutes)
- **Exit ticket**: 3 multiple-choice questions covering today's material
- **Group share**: One thing you learned, one question you still have
- Preview tomorrow's lesson and how it builds on {topic}

## Differentiation
- **For struggling students**: Provide sentence frames, vocabulary cards, and graphic organizers
- **For advanced students**: Extension activity with higher-order thinking questions and research prompts

## Homework
Review the class notes on {topic} and complete the reflection journal entry. Be prepared to share one key takeaway at the start of tomorrow's class.

---
*Generated by Nisa Lesson Planner*`,

  followup: `Great question! Here's some additional guidance on **{topic}**:

**Key Points to Emphasize:**
- Focus on visual aids when explaining this concept to students
- Use the "I Do, We Do, You Do" gradual release framework
- Allow extra time for student questions and misconceptions

**Common Misconceptions:**
Students often struggle with the nuances of {topic}. Make sure to explicitly address:

1. The difference between related but distinct concepts
2. Why certain processes work the way they do
3. How to avoid the most common mistakes in understanding

**Scaffolding Suggestions:**
- Start with concrete examples before moving to abstract ideas
- Use analogies that connect to students' lived experiences
- Provide sentence starters for written responses

**Additional Resources:**
- Khan Academy has excellent supplemental videos on this topic
- The National Education Association has free lesson supplements
- Consider using Kahoot! or Blooket for an interactive review game

Would you like me to create a more detailed breakdown of any specific section?`,
};

function generateResponse(topic: string, isFollowup: boolean): string {
  const template = isFollowup ? LESSON_PLANS.followup : LESSON_PLANS.default;
  return template.replace(/\{topic\}/g, topic);
}

export async function POST(req: Request) {
  const { messages } = await req.json();

  const userMessages = messages.filter(
    (m: { role: string }) => m.role === "user",
  );
  const isFollowup = userMessages.length > 1;

  // Extract topic from the last user message
  const lastUserMessage = userMessages[userMessages.length - 1];
  const topic =
    lastUserMessage?.parts?.find((p: { type: string }) => p.type === "text")
      ?.text ||
    lastUserMessage?.content ||
    "General Topic";

  const responseText = generateResponse(topic, isFollowup);

  // Split into words for token-by-token streaming
  const words = responseText.split(" ");

  const stream = createUIMessageStream({
    async execute({ writer }) {
      const textId = "text-0";

      // Simulate variable first-token latency (like a real LLM "thinking")
      await new Promise((resolve) =>
        setTimeout(resolve, Math.random() * 400),
      );

      writer.write({ type: "start" });
      writer.write({ type: "start-step" });
      writer.write({ type: "text-start", id: textId });

      for (const word of words) {
        // Simulate realistic LLM token latency (20-60ms per token)
        await new Promise((resolve) =>
          setTimeout(resolve, 20 + Math.random() * 40),
        );
        writer.write({ type: "text-delta", delta: `${word} `, id: textId });
      }

      writer.write({ type: "text-end", id: textId });
      writer.write({ type: "finish-step" });
      writer.write({ type: "finish", finishReason: "stop" });
    },
  });

  return createUIMessageStreamResponse({ stream });
}
